### ISSUE TITLE
Hier.part in Statistik 3 ersetzen

### ISSUE THREAD

**Issue by DLND8** [ResearchMethods-ZHAW/Statistik#35]
Neuer Code hier: https://github.com/ResearchMethods-ZHAW/HS23/commit/114ab9bd3eab611a53e5e98b1dc096b234a945b5

**Comment by ratnanil** [comment]
@DLND8: kannst du das übernehmen, weil du auch https://github.com/ResearchMethods-ZHAW/HS23/commit/114ab9bd3eab611a53e5e98b1dc096b234a945b5 umgesetzt hast? Muss man da auch code outputs anpassen?

**Comment by DLND8** [comment]
```{.r}
library("relaimpo")

lm_1 <- lm(ABUND~YR.ISOL+ AREA +  DIST + LDIST + GRAZE + ALT, data = loyn)

metrics <- calc.relimp(lm_1, type = c("lmg", "first", "last","betasq", "pratt"))
IJ <- cbind(I = metrics$lmg, J = metrics$first - metrics$lmg, Total = metrics$first)

IJ
```

```{.default}
$IJ
                 I            J       Total
YR.ISOL 0.11827368  0.135095338 0.253369016
AREA    0.02359769  0.041923060 0.065520747
DIST    0.02566349  0.030085610 0.055749104
LDIST   0.01270789 -0.005112317 0.007595573
GRAZE   0.25879164  0.207030145 0.465821782
ALT     0.07275743  0.076112117 0.148869552
```

_Der grösste Teil (61%) der insgesamt erklärten Varianz dieses Drei-Parameter-Models wird hier also durch den Faktor Grazing erklärt._

-------------------------------------------------------

Ich habe den Code und Output mal angepasst. Jedoch passt der _kursiv geschriebene Text_ nicht mehr. @Hepi2  Kannst du hierfür eine Vorschlag nach Absprache mit Jürgen machen?

**Comment by DLND8** [comment]
done with https://github.com/ResearchMethods-ZHAW/Statistik/commit/a00be298844b6729b94e0d8923e303d987611bce
