### ISSUE TITLE
Fehlende Informationen zu Bild

### ISSUE THREAD

**Issue by DLND8** [ResearchMethods-ZHAW/Statistik#36]
![image](https://github.com/ResearchMethods-ZHAW/Statistik/assets/18243911/0c9cf895-9c90-4648-add0-c63f354bea10)

https://github.com/ResearchMethods-ZHAW/Statistik/blob/0ef874e1bd36b7f9f18ce78a9d0ca834ae6ea71f/Statistik_3.qmd#L31

**Comment by ratnanil** [comment]
![Screenshot from 2023-11-06 15-01-33](https://github.com/ResearchMethods-ZHAW/Statistik/assets/12532091/d7a91257-c829-46df-8804-6ad828495a3f)
 

p. 63
