### ISSUE TITLE
1:1 Vergleich

### ISSUE THREAD

**Issue by ratnanil** [ResearchMethods-ZHAW/Statistik#5]
Man muss das Docx 1:1 mit dem Html vergleichen und dabei den code anpassen. Bisher habe ich alles was so graue blöcke sind in callouts verwandlet (ohne `-note`). Formeln habe ich zu einem Grossteil angepasst und Tabellen eingepflegt. Aktuell bin ich bei Zeile 2526 in index.qmd. (`<!-- HIER WEITERMACHEN -->`).

**Comment by ratnanil** [comment]
Neu: Weitermachen bei Statistik_4.qmd

**Comment by ratnanil** [comment]
HTML

- [x] Statistik 1
- [x] Statistik 2
- [x] Statistik 3
- [ ] Statistik 4
- [ ] Statistik 5
- [ ] Statistik 6
- [ ] Statistik 7
- [ ] Statistik 8

PDF

- [ ] Statistik 1
- [ ] Statistik 2
- [ ] Statistik 3
- [x] Statistik 4
- [ ] Statistik 5
- [ ] Statistik 6
- [ ] Statistik 7
- [ ] Statistik 8

**Comment by DLND8** [comment]
![image](https://github.com/ResearchMethods-ZHAW/Statistik/assets/18243911/f88fc655-dbb4-467a-882d-cd64f6d9bdb6)

Statistik Linie 371-377

Grösse von Bilder zu gross in PDF

**Comment by DLND8** [comment]
![image](https://github.com/ResearchMethods-ZHAW/Statistik/assets/18243911/dccec37c-e522-47a2-ac6c-4a19f951ffab)

Statistik 3 Linie 235 - 245

Grösse von Bilder zu gross in PDF

**Comment by DLND8** [comment]
![image](https://github.com/ResearchMethods-ZHAW/Statistik/assets/18243911/02280c3b-5967-4def-8ac8-88a491c2aedb)

Statistik 6 Linie 182 - 188

Grösse von Bilder stimmen nicht
